// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2H2mYtV1VeujxDqmIzqxy4KiD6QaBuO0',
    appId: '1:682099681529:web:3e8d4cce7356cb49331a28',
    messagingSenderId: '682099681529',
    projectId: 'fleamarket-ecf89',
    authDomain: 'fleamarket-ecf89.firebaseapp.com',
    storageBucket: 'fleamarket-ecf89.appspot.com',
    measurementId: 'G-L1JX71XH3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoWvgwMeDuO7txXgGDEt0dHKm2SV-nk-c',
    appId: '1:682099681529:android:e4cdf74da849beba331a28',
    messagingSenderId: '682099681529',
    projectId: 'fleamarket-ecf89',
    authDomain: 'fleamarket-ecf89.firebaseapp.com',
    storageBucket: 'fleamarket-ecf89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChI5pai2LmVst3FUSv6pH6zaFpYaLwAEc',
    appId: '1:682099681529:ios:57ae975ac1a43841331a28',
    messagingSenderId: '682099681529',
    projectId: 'fleamarket-ecf89',
    storageBucket: 'fleamarket-ecf89.appspot.com',
    androidClientId: '682099681529-7p28ph1mj33qsjf0nambenkv34pmk948.apps.googleusercontent.com',
    iosClientId: '682099681529-u0cdvmcgcu1elqr8lh2o2v5l8i67dqco.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChI5pai2LmVst3FUSv6pH6zaFpYaLwAEc',
    appId: '1:682099681529:ios:bda4332df616208b331a28',
    messagingSenderId: '682099681529',
    projectId: 'fleamarket-ecf89',
    storageBucket: 'fleamarket-ecf89.appspot.com',
    androidClientId: '682099681529-7p28ph1mj33qsjf0nambenkv34pmk948.apps.googleusercontent.com',
    iosClientId: '682099681529-5hho4vflsi1ag28imcedc0fq3gf9uurq.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
